<?php $this->headlink()->appendStylesheet('font-awesome-4.1.0/css/font-awesome.min.css')?>
<?php $this->headlink()->appendStylesheet('/css/plugins/morris.css')?>
<?php $this->headlink()->appendStylesheet('js/plugins/datePicker/css/datepicker3.css')?>
<?php $this->headlink()->appendStylesheet("js/plugins/dropzone/css/dropzone.css")?>

<div id="page-wrapper" style="min-height: 186px;">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Reports</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row text-center">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label><span type="button" class="btn btn-primary btn-circle"><i class="">1</i></span> Select Categories</label>
                        <br><br>
                        <select multiple="" id="reportsCategory" name="categories_id" class="form-control">
                            <?php foreach ($category as $res):?>
                            	<option value="<?php echo $res['id'];?>"><?php echo  $res['description'] ?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label><span type="button" class="btn btn-primary btn-circle"><i class="">2</i></span> Select Date Range</label>
                        <br><br>
                        <div class="input-daterange input-group" id="datepicker" style="margin: 0 auto;">
                            <input type="text" class="input-sm form-control" name="start" id="startTime">
                            <span class="input-group-addon">to</span>
                            <input type="text" class="input-sm form-control" name="end" id="endTime">
                        </div>
                        <br>
                        <button type="button" class="btn btn-outline btn-default" id="viewReport">View Report</button>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-lg-12">
                <h4>July 1st - August 1st 2014</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12" >
                    <div id="graph"></div>
                </div>
            </div>
        </div>
<?php $this->headscript()->appendFile('/js/plugins/datePicker/js/bootstrap-datepicker.js?v='.time())?>

<?php $this->headscript()->appendFile('http://cdn.oesmith.co.uk/morris-0.4.1.min.js')?>
<?php $this->headscript()->appendFile('http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js')?>
<?php $this->headscript()->appendFile('/js/reports.js')?>
