<?php $this->headlink()->appendStylesheet('font-awesome-4.1.0/css/font-awesome.min.css')?>
<?php $this->headlink()->appendStylesheet('js/plugins/datePicker/css/datepicker3.css')?>
<?php $this->headlink()->appendStylesheet("js/plugins/dropzone/css/dropzone.css")?>
<div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Settings</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                            <!-- Nav tabs -->
                            <ul class="nav nav-pills">
                                <li class="active"><a href="#General-pills" data-toggle="tab">General</a>
                                </li>
                                <!-- auth -->
                                 <?php if($userInfo->company_id == '0'):?>
                                <li><a href="#Companies-pills" data-toggle="tab">Companies</a>
                                </li>
                                <?php endif;?>
                                <li><a href="#Users-pills" data-toggle="tab">Users</a>
                                </li>
                                <li><a href="#Categories-pills" data-toggle="tab">Categories</a>
                                </li>
                                <li><a href="#Currency-pills" data-toggle="tab">Currency</a>
                                </li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div class="tab-pane fade in active" id="General-pills">
                                    <h4>General Settings</h4>
                                    <p>None.</p>
                                </div>
                                <?php if($userInfo->company_id == '0'):?>
                                <div class="tab-pane fade" id="Companies-pills">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <h4>Manage Companies</h4>
                                        </div>
                                        <div class="col-lg-6">
                                            <!-- Button trigger modal -->
                                            <button class="btn btn-success btn-xs pull-right" data-toggle="modal" data-target="#addCompaniesModal">
                                                Add Company
                                            </button>
                                            <!-- Add User Modal -->
                                            <div class="modal fade" id="addCompaniesModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                            <h4 class="modal-title" id="myModalLabel">Add Company</h4>
                                                        </div>
                                                        <div class="modal-body">
                                                            <div class="row">
                                                                <div class="col-lg-12">
                                                                    <div class="form-group">
                                                                        <label>Company Name</label>
                                                                        <input class="form-control" name="name" placeholder="Company Name">
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-12">
                                                                    <div class="form-group">
                                                                        <label>E-Mail Address</label>
                                                                        <input class="form-control" name="email" placeholder="email@address.com">
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>First Name</label>
                                                                        <input class="form-control" name="firstName" placeholder="First Name">
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>Last Name</label>
                                                                        <input class="form-control" name="lastName"placeholder="Last Name">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                            <button type="button" class="btn btn-primary">Add Company</button>
                                                        </div>
                                                    </div>
                                                    <!-- /.modal-content -->
                                                </div>
                                                <!-- /.modal-dialog -->
                                            </div>
                                            <!-- /.modal -->
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                             <br />
                                                <div class="panel panel-default">
                                                    <div class="panel-heading">
                                                        Company List
                                                    </div>
                                                    <!-- /.panel-heading -->
                                                    <div class="panel-body">
                                                        <div class="table-responsive">
                                                            <table class="table table-hover">
                                                                <thead>
                                                                    <tr>
                                                                        <th>#</th>
                                                                        <th>Company</th>
                                                                        <th>Users</th>
                                                                        <th>Action</th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                	<?php foreach($companyies as $valuess):?>
                                                                	
                                                                    <tr>
                                                                        <td><?php echo $valuess['id'];?></td>
                                                                        <td><?php echo $valuess['name'];?></td>
                                                                        <td><?php echo $valuess['companyCount']?></td>
                                                                        <td><button type="button"  class="btn btn-warning btn-circle" data-toggle="modal" data-target="#companyDeleteModal"><i class="fa fa-times"></i></button></td>
                                                                    </tr>
                                                                    <?php endforeach;?>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                        <!-- /.table-responsive -->
                                                    </div>
                                                    <!-- /.panel-body -->
                                                </div>
                                                <!-- /.panel -->
                                            </div>
                                             <!-- Add User Modal -->
                                            <div class="modal fade" id="companyDeleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                            <h4 class="modal-title" id="myModalLabel">Delete Company</h4>
                                                        </div>
                                                        <div class="modal-body">
                                                            <div class="row">
                                                                <div class="col-lg-12 text-center">
                                                                    <p class="lead">Are you sure you want to delete this Company?<br /> All recepit data and users will be deleted</p>
                                                                    
                                                                    <select class="form-control">
                                                                        <option>Select</option>
                                                                        <option>Yes</option>
                                                                        <option>No</option>
                                                                    </select>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                                            <button type="button" class="btn btn-danger">Delete Company</button>
                                                        </div>
                                                    </div>
                                                    <!-- /.modal-content -->
                                                </div>
                                                <!-- /.modal-dialog -->
                                            </div>
                                            <!-- /.modal -->
                                    </div>
                                </div>
                                <?php endif;?>
                                <div class="tab-pane fade" id="Users-pills">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <h4>Manage Users</h4>
                                        </div>
                                        <div class="col-lg-6">
                                            <!-- Button trigger modal -->
                                            <button class="btn btn-success btn-xs pull-right" data-toggle="modal" data-target="#addUserModal">
                                                Add User
                                            </button>
                                            <!-- Add User Modal -->
                                            <div class="modal fade" id="addUserModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                            <h4 class="modal-title" id="myModalLabel">Add User</h4>
                                                        </div>
                                                        <div class="modal-body">
                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>Full Name</label>
                                                                        <input class="form-control" name="fullName" id="fullName" placeholder="Full name">
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>Username</label>
                                                                        <input class="form-control" name="username" id="username" placeholder="Username">
                                                                    </div>
                                                                </div>

                                                            </div>
                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>Password</label>
                                                                        <input class="form-control" id="password" name="password" placeholder="Password">
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>Confirm Password</label>
                                                                        <input class="form-control" name="enterPassword" id="enterPassword" placeholder="Password">
                                                                    </div>
                                                                </div>
                                                                <?php if($userInfo->company_id == "0"):?>
																	<div class="col-lg-12">
	                                                                    <div class="form-group">
	                                                                        <label>Company</label>
	                                                                        <select class="form-control" name="company_id" id="user_company_id">
	                                                                        	<?php foreach($companyies as $res):?>
	                                                                        		<option value="<?php echo $res['id'];?>"><?php echo $res['name'];?></option>
																				<?php endforeach;?>
																			</select>
	                                                                    </div>
	                                                                </div>
                                                                <?php endif;?>
                                                            </div>

                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                            <button type="button" class="btn btn-primary" id="addUserSubmit">Add User</button>
                                                        </div>
                                                    </div>
                                                    <!-- /.modal-content -->
                                                </div>
                                                <!-- /.modal-dialog -->
                                            </div>
                                            <!-- /.modal -->
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                             <br />
                                                <div class="panel panel-default">
                                                    <div class="panel-heading">
                                                        User List
                                                    </div>
                                                    <!-- /.panel-heading -->
                                                    <div class="panel-body">
                                                        <div class="table-responsive">
                                                            <table class="table table-hover" id="userList">
                                                                <thead>
                                                                    <tr>
                                                                        <th>#</th>
                                                                        <th>First Name</th>
                                                                        <th>Last Name</th>
                                                                        <th>Username</th>
                                                                        <th>Action</th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
		                                                                <?php foreach($users as $user) :?>
																	<tr>
                                                                        <td><?php echo $user->id;?></td>
                                                                        <td><?php echo $user->fullName;?></td>
                                                                        <td><?php echo $user->fullName;?></td>
                                                                        <td><?php echo $username = $user->username?$user->username:$user->email;?></td>
	                                                                        
                                                                        	<td>
                                                                        	<?php if($user->id != '1'): ?>
                                                                        		<button type="button"  class="btn btn-warning btn-circle userDelete" userid = "<?php echo $user->id;?>" data-toggle="modal" data-target="#userDeleteModal"><i class="fa fa-times"></i></button>
                                                                        	<?php endif;?>
                                                                        	</td>
	                                                                    </tr>
	                                                                <?php endforeach;?>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                        <!-- /.table-responsive -->
                                                    </div>
                                                    <!-- /.panel-body -->
                                                </div>
                                                <!-- /.panel -->
                                            </div>
                                             <!-- Add User Modal -->
                                            <div class="modal fade" id="userDeleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                            <h4 class="modal-title" id="myModalLabel">Delete User</h4>
                                                        </div>
                                                        <div class="modal-body">
                                                            <div class="row">
                                                                <div class="col-lg-12 text-center">
                                                                    <p class="lead">Are you sure you want to delete this user?</p>
                                                                    
                                                                    <h4>Username Here</h4>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                                            <button type="button" id="enterUserDelete" class="btn btn-danger">Delete User</button>
                                                        </div>
                                                    </div>
                                                    <!-- /.modal-content -->
                                                </div>
                                                <!-- /.modal-dialog -->
                                            </div>
                                            <!-- /.modal -->
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Categories-pills">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <h4>Manage Categories</h4>
                                        </div>
                                        <div class="col-lg-6">
                                            <!-- Button trigger modal -->
                                            <button class="btn btn-success btn-xs pull-right" data-toggle="modal" data-target="#addCategoryModal">
                                                Add Category
                                            </button>
                                            <!-- Add User Modal -->
                                            <div class="modal fade" id="addCategoryModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                            <h4 class="modal-title" id="myModalLabel">Add Category</h4>
                                                        </div>
                                                        <div class="modal-body">
                                                            <div class="row">
                                                                <div class="col-lg-12">
                                                                    <div class="form-group">
                                                                        <label>Category</label>
                                                                        <input class="form-control" id="inputCategory" name="category" placeholder="Full name">
                                                                    </div>
                                                                </div>
                                                                <?php if($userInfo->company_id == "0"):?>
																	<div class="col-lg-12">
	                                                                    <div class="form-group">
	                                                                        <label>Company</label>
	                                                                        <select class="form-control" name="company_id" id="category_company_id">
	                                                                        	<?php foreach($companyies as $res):?>
	                                                                        		<option value="<?php echo $res['id'];?>"><?php echo $res['name'];?></option>
																				<?php endforeach;?>
																			</select>
	                                                                    </div>
	                                                                </div>
                                                                <?php endif;?>
                                                            </div>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                            <button type="button" class="btn btn-primary" id="addCategorySubmit">Add Category</button>
                                                        </div>
                                                    </div>
                                                    <!-- /.modal-content -->
                                                </div>
                                                <!-- /.modal-dialog -->
                                            </div>
                                            <!-- /.modal -->
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                             <br />
                                                <div class="panel panel-default">
                                                    <div class="panel-heading">
                                                        Category List
                                                    </div>
                                                    <!-- /.panel-heading -->
                                                    <div class="panel-body">
                                                        <div class="table-responsive">
                                                            <table class="table table-hover" id="categoryList">
                                                                <thead>
                                                                    <tr>
                                                                        <th>#</th>
                                                                        <th>Category</th>
                                                                        <th>Action</th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                	<?php foreach($categorys as $res):?>
                                                                    <tr>
                                                                        <td><?php echo $res['id'];?></td>
                                                                        <td><?php echo $res['description'];?></td>
                                                                        <td><button type="button" class="btn btn-warning btn-circle" data-toggle="modal" data-target="#categoryDeleteModal"><i class="fa fa-times"></i></button></td>
                                                                    </tr>
                                                                    <?php endforeach;?>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                        <!-- /.table-responsive -->
                                                    </div>
                                                    <!-- /.panel-body -->
                                                </div>
                                                <!-- /.panel -->
                                            </div>
                                             <!-- Add User Modal -->
                                            <div class="modal fade" id="categoryDeleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                            <h4 class="modal-title" id="myModalLabel">Delete Category: NAME</h4>
                                                        </div>
                                                        <div class="modal-body">
                                                            <div class="row">
                                                                <div class="col-lg-12 text-center">
                                                                    <p class="lead">Are you sure you want to delete this Category?<br /> Please select a category to replace the exisiting entries</p>
                                                                    
                                                                    <select class="form-control" id="categoryReplaceId">
                                                                        <option value="0">Select</option>
                                                                        <?php foreach($categorys as $res):?>
                                                                        <option value="<?php echo $res['id']?>"><?php echo $res['description']?></option>
                                                                        <?php endforeach;?>
                                                                    </select>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                                            <button type="button" class="btn btn-danger">Delete Category</button>
                                                        </div>
                                                    </div>
                                                    <!-- /.modal-content -->
                                                </div>
                                                <!-- /.modal-dialog -->
                                            </div>
                                            <!-- /.modal -->
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="Currency-pills">
                                    <div class="row">
                                        <div class="col-lg-6">
                                            <h4>Manage Currencies</h4>
                                        </div>
                                        <div class="col-lg-6">
                                            <!-- Button trigger modal -->
                                            <button class="btn btn-success btn-xs pull-right" data-toggle="modal" data-target="#addCurrencyModal">
                                                Add Currency
                                            </button>
                                            <!-- Add User Modal -->
                                            <div class="modal fade" id="addCurrencyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                            <h4 class="modal-title" id="myModalLabel">Add Currency</h4>
                                                        </div>
                                                        <div class="modal-body">
                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>Currency Short Name</label>
                                                                        <input class="form-control" id="inputCurrencyCode" name="currencyCode" placeholder="USD">
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>Description</label>
                                                                        <input class="form-control" id="inputContry" name="contry" name="" placeholder="American Dollars">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            
                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>Average Yearly Value against USD</label>
                                                                        <input class="form-control" id="inputUSDvalue" name="USDvalue" placeholder="0.7">
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>Applicable Year</label>
                                                                        <input class="form-control" id="inputApplicableYear" name="applicableYear" placeholder="2014">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <?php if($userInfo->company_id == "0"):?>
                                                            	<div class="row">
																	<div class="col-lg-12">
	                                                                    <div class="form-group">
	                                                                        <label>Company</label>
	                                                                        <select class="form-control" name="company_id" id="currency_company_id">
	                                                                        	<?php foreach($companyies as $res):?>
	                                                                        		<option value="<?php echo $res['id'];?>"><?php echo $res['name'];?></option>
																				<?php endforeach;?>
																			</select>
	                                                                    </div>
	                                                                </div>
	                                                             </div>
                                                             <?php endif;?>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                            <button type="button" class="btn btn-primary" id="addCurrencySubmit">Add Currency</button>
                                                        </div>
                                                    </div>
                                                    <!-- /.modal-content -->
                                                </div>
                                                <!-- /.modal-dialog -->
                                            </div>
                                            <!-- /.modal -->
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12">
                                             <br />
                                                <div class="panel panel-default">
                                                    <div class="panel-heading">
                                                        Currency List
                                                    </div>
                                                    <!-- /.panel-heading -->
                                                    <div class="panel-body">
                                                        <div class="table-responsive">
                                                            <table class="table table-hover">
                                                                <thead>
                                                                    <tr>
                                                                        <th>#</th>
                                                                        <th>Currency Code</th>
                                                                        <th>Description</th>
                                                                        <th>Yearly Avg (USD)</th>
                                                                        <th>Applicable Year</th>
                                                                        <th>Action</th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                	<?php foreach ($currencys as $res):?>
                                                                    <tr>
                                                                        <td><?php echo $res['id'];?></td>
                                                                        <td><?php echo $res['currencyCode'];?></td>
                                                                        <td><?php echo $res['contry'];?></td>
                                                                        <td><?php echo $res['USDvalue'];?></td>
                                                                        <td><?php echo $res['applicableYear'];?></td>
                                                                        <td>
                                                                            <button type="button" class="btn btn-primary btn-circle edit-currency" data-toggle="modal" data-target="#currencyEditModal"><i class="fa fa-list"></i></button>
                                                                            <button type="button" class="btn btn-warning btn-circle delete-currency" data-toggle="modal" data-target="#currencyDeleteModal"><i class="fa fa-times"></i></button></td>
                                                                    </tr>
                                                                   <?php endforeach;?>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                        <!-- /.table-responsive -->
                                                    </div>
                                                    <!-- /.panel-body -->
                                                </div>
                                                <!-- /.panel -->
                                            </div>
                                             <!-- Add User Modal -->
                                            <div class="modal fade" id="currencyDeleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                            <h4 class="modal-title" id="myModalLabel">Delete Category: NAME</h4>
                                                        </div>
                                                        <div class="modal-body">
                                                            <div class="row">
                                                                <div class="col-lg-12 text-center">
                                                                    <p class="lead">Are you sure you want to delete this Currency?<br /> Please select a currency to replace the exisiting entries</p>
                                                                    
                                                                    <select class="form-control col-lg-4">
                                                                        <option>Select</option>
                                                                        <option>USD</option>
                                                                        <option>RMB</option>
                                                                        <option>HKD</option>
                                                                    </select>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                                            <button type="button" class="btn btn-danger">Delete Category</button>
                                                        </div>
                                                    </div>
                                                    <!-- /.modal-content -->
                                                </div>
                                                <!-- /.modal-dialog -->
                                            </div>
                                            <!-- /.modal -->

                                             <!-- Add User Modal -->
                                            <div class="modal fade" id="currencyEditModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                            <h4 class="modal-title" id="myModalLabel">Edit Currency: DESCRIPTION</h4>
                                                        </div>
                                                        <div class="modal-body">
                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>Currency Short Name</label>
                                                                        <input class="form-control" id="editCurrencyCode" name="currencyCode" placeholder="USD">
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>Description</label>
                                                                        <input class="form-control" id="editContry" name="contry" placeholder="American Dollars">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>Average Yearly Value against USD</label>
                                                                        <input class="form-control" id="editUSDvalue" name="USDvalue" placeholder="0.7">
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <div class="form-group">
                                                                        <label>Applicable Year</label>
                                                                        <input class="form-control" id="editApplicableYear" name="applicableYear" placeholder="2014">
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                                            <button type="button" class="btn btn-primary">Save Changes</button>
                                                        </div>
                                                    </div>
                                                    <!-- /.modal-content -->
                                                </div>
                                                <!-- /.modal-dialog -->
                                            </div>
                                            <!-- /.modal -->
                                    </div>
                                </div>
                            </div>

                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
<?php $this->headscript()->appendFile('/js/settings.js?v='.time())?>