<?php $this->headlink()->appendStylesheet('font-awesome-4.1.0/css/font-awesome.min.css')?>
<?php $this->headlink()->appendStylesheet('js/plugins/datePicker/css/datepicker3.css')?>
<?php $this->headlink()->appendStylesheet("js/plugins/dropzone/css/dropzone.css")?>
<?php $this->headlink()->appendStylesheet("/css/plugins/jcrop/jquery.Jcrop.css")?>

 <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Manage Invoices</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- Nav tabs -->
                            <ul class="nav nav-pills">
                                <li class="active"><a href="#manage" data-toggle="tab">Manage</a>
                                </li>
                                <li><a href="#review" data-toggle="tab">Review</a>
                                </li>
                                <li><a href="#upload" data-toggle="tab">Upload</a>
                                </li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">
                                <div class="tab-pane fade in active" id="manage">
                                    <h4>Manage Receipts</h4>
                                    <div class="col-lg-8">
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                Receipt Image
                                                <button type="button" class="btn btn-success btn-circle pull-right" style="margin-top: -5px;"><i class="fa fa-check"></i></button>
                                            </div>
                                            <div class="panel-body" id="warpImage"style="position:relative;">
                                                <img src="img/sample.png" class="img-responsive"  id="skipImagePath">
                                                <input type="hidden" id="startX" value="0" />
                                                <input type="hidden" id="startY" value="0" />
                                                <input type="hidden" id="endX" value="0" />
                                                <input type="hidden" id="endY" value="0" />
                                                
                                            </div>
                                            <div class="panel-footer">
                                                <div style="width:100px; margin:0 auto; position:relative;">
                                                    <button type="button" style="top:0" class="btn btn-default btn-circle" id="jcrop_image"><i class="fa fa-crop"></i></button>
                                                    <button type="button" style="top:0" class="btn btn-default btn-circle" id="skipImageLeft"><i class="fa fa-rotate-left"></i></button>
                                                    <button type="button" style="top:0" class="btn btn-default btn-circle" id="skipImageRight"><i class="fa fa-rotate-right"></i></button>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="col-lg-4">
                                        <div class="panel panel-primary">
                                            <div class="panel-heading">
                                                Receipt Data
                                            </div>
                                            <div class="panel-body">
                                                <p>Please input all receipt information</p>
                                                <div class="form-group">
                                                    <input type="hidden" id="skipInvoicesId" value="" />
                                                </div>
                                                <div class="form-group">
                                                    <label>Receipt Category</label>
                                                    <select id="skipSelectCompanys" class="form-control">
                                                        <option>Tools</option>
                                                        <option>Office furniture</option>
                                                        <option>Food Expense</option>
                                                        <option>Computers</option>
                                                    </select>
                                                </div>

                                                <div class="form-group">
                                                    <label>Purchase Date</label>
                                                    <div id="manageInvoiceDate" class="input-group date">
                                                        <input type="text" class="form-control" id="skipPurchaseDate"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                                                    </div>
                                                </div>

		                                        <div class="form-group">
		                                            <label>Recepit Value</label>
			                                            <div class="row">
														  <div class="form-group col-lg-8">
                                                        	<input type="text" class="form-control" id="skipValue" placeholder="88.00">
														  </div>
														  <div class="col-lg-4">
														    <select id= "skipSelectCurrency" id="" class="form-control">
				                                                <option>RMB</option>
				                                                <option>HKD</option>
				                                                <option>USD</option>
				                                                <option>AUD</option>
				                                                <option>EUR</option>
				                                            </select>
														  </div>
														  
														</div>
													</div>


                                                <div class="form-group">
                                                    <label>Recepit Number</label>
                                                    <div class="form-group input-group">
                                                        <span class="input-group-addon">#</span>
                                                        <input type="text" class="form-control" id="skipNumber" placeholder="1234ABCD">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label>Recepit Description</label>
                                                    <input type="text" class="form-control" id="skipDescription" placeholder="Description">
                                                </div>


                                            </div>
                                            <div class="panel-footer">
                                                
                                                    <button type="button" class="btn btn-default btn-circle" id="skipHistory"><i class="fa fa-history"></i></button>
                                                
                                            </div>
                                        </div>
                                        <hr />

                                        <button type="button" class="btn btn-warning" id="skipNextButton">Skip & Next</button>
                                        <button type="button" class="btn btn-success pull-right" id="saveNextButton">Save & Next</button>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="review">
                                    <h4>Review Receipts</h4>
                                    <p>Below is a list of confirmed receipts entered in to the system.</p>
                                    <hr />
                                    <div class="row">
                                        <div class="col-lg-12">

                                            <div class="table-responsive">
                                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                                    <thead>
                                                        <tr>
                                                            <th>System ID</th>
                                                            <th>Purchase Date</th>
                                                            <th>Validated Date</th>
                                                            <th>Category</th>
                                                            <th>Value</th>
                                                            <th>Receipt Number</th>
                                                            <th>Description</th>
                                                            <th>Action</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        
                                                    </tbody>
                                                </table>
                                            </div>
                                            <!-- /.table-responsive -->
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="upload">
                                    <h4>Upload Receipts</h4>
                                    <p>Drag and drop images to upload for management.</p>
                                    <hr />
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <form action="/file-upload" class="dropzone" id="cloggerDropzone"></form>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.col-lg-12 -->
                            </div>
                </div>
            </div>
        </div>
        <!-- /#page-wrapper -->
        <!-- Add User Modal -->
        <div class="modal fade" id="editReceipt" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog" style="width: 51%;">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel">Edit Receipt Information</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        Receipt Image
                                        <button type="button" class="btn btn-success btn-circle pull-right" style="margin-top: -5px;"><i class="fa fa-check"></i></button>
                                    </div>
                                    <div class="panel-body">
                                        <img src="" id="invoicesImagePath" class="img-responsive">
                                    </div>
                                    <div class="panel-footer">
                                        <div style="width:100px; margin:0 auto;">
                                            <button type="button" class="btn btn-default btn-circle"><i class="fa fa-crop"></i></button>
                                            <button type="button" class="btn btn-default btn-circle" id="rotateLToolsButton" ><i class="fa fa-rotate-left"></i></button>
                                            <button type="button" class="btn btn-default btn-circle" id="rotateRToolsButton"><i class="fa fa-rotate-right"></i></button>
                                        </div>

                                    </div>
                                </div>
                            </div>
                                <div class="col-lg-4">
                                    <div class="panel panel-primary">
                                        <div class="panel-heading">
                                            Receipt Data
                                        </div>
                                        <div class="panel-body">
                                            <p>Please input all receipt information</p>
                                            <input type="hidden" id="reviewInvoicesId" name="id" value="">
                                            <div class="form-group">
                                                <label>Receipt Category</label>
                                                <select id="editCategorys" class="form-control" name="categorys">
                                                </select>
                                            </div>

											<div class="form-group">
                                                    <label>Purchase Date</label>
                                                    <div id="reviewInvoiceDate" class="input-group date">
                                                        <input type="text" id="reviewInvoicePurchaseDate" style="z-index:1000;position:relative;" name="purchaseDate" class="form-control" name="purchaseDate" id="purchaseDate"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                                                    </div>
                                                </div>
                                             <div class="form-group">
                                                <label>Recepit Value (RMB)</label>
                                                <div class="form-group input-group">
                                                    <span class="input-group-addon">$</span>
                                                    <input type="text" class="form-control" id="reviewInvoicesValue" name="value" placeholder="88.00">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Recepit Number</label>
                                                <div class="form-group input-group">
                                                    <span class="input-group-addon">#</span>
                                                    <input type="text" class="form-control" id="reviewInvoicesNumber" name="number" placeholder="1234ABCD">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Recepit Description</label>
                                                <input type="text" class="form-control" id="reviewInvoicesDescription" name="description" placeholder="Description">
                                            </div>
                                        </div>
                                        <div class="panel-footer">
                                            <button type="button" class="btn btn-default btn-circle"><i class="fa fa-history"></i></button>
                                        </div>
                                    </div>
                                    <hr />
                                </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-success" >Update Information</button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
    </div>
    <!-- /#wrapper -->




<?php $this->headscript()->appendFile('/js/plugins/dataTables/jquery.dataTables.js')?>
<?php $this->headscript()->appendFile('/js/plugins/dataTables/dataTables.bootstrap.js')?>
<?php $this->headscript()->appendFile('/js/plugins/dropzone/dropzone.js')?>
<?php $this->headscript()->appendFile('/js/plugins/datePicker/js/bootstrap-datepicker.js')?>

<?php $this->headscript()->appendFile('/js/plugins/jcrop/jquery.Jcrop.js')?>
<?php $this->headscript()->appendFile('/js/invoices.js?v='.time())?>