<?php $this->headlink()->appendStylesheet('font-awesome-4.1.0/css/font-awesome.min.css')?>
<?php $this->headlink()->appendStylesheet('js/plugins/datePicker/css/datepicker3.css')?>
<?php $this->headlink()->appendStylesheet("js/plugins/dropzone/css/dropzone.css")?>
<!-- Page Content -->
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Welcome Username</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->